# Generated by Django 3.0.6 on 2020-07-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0004_auto_20200701_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(default='Shorts'),
            preserve_default=False,
        ),
    ]
