# Generated by Django 3.0.6 on 2020-07-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0005_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
