# Generated by Django 3.0.6 on 2020-07-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0007_auto_20200701_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='Description Coming Soon..!!'),
            preserve_default=False,
        ),
    ]
